import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

import type { JournalEntry } from "@/context/JournalContext";

const MOOD_EMOJI: Record<string, string> = {
  great: "😄",
  good: "🙂",
  okay: "😐",
  bad: "😔",
  awful: "😢",
};

function formatDate(dateStr: string): string {
  try {
    const d = new Date(dateStr + "T12:00:00");
    return d.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
  } catch {
    return dateStr;
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\n/g, "<br>");
}

export async function exportJournalAsPDF(entries: JournalEntry[]): Promise<void> {
  const sorted = [...entries].sort((a, b) => a.date.localeCompare(b.date));

  const entriesHtml = sorted
    .map((e) => {
      const emoji = MOOD_EMOJI[e.mood] ?? "📝";
      const thoughtsBlock = e.content
        ? `<div class="field"><div class="field-label">Thoughts</div><div class="field-body">${escapeHtml(e.content)}</div></div>`
        : "";
      const reflectionBlock = e.reflection
        ? `<div class="field"><div class="field-label">Reflection</div><div class="field-body">${escapeHtml(e.reflection)}</div></div>`
        : "";
      return `
        <div class="entry">
          <div class="entry-header">
            <span class="entry-date">${formatDate(e.date)}</span>
            <span class="mood-badge">${emoji} ${e.mood.charAt(0).toUpperCase() + e.mood.slice(1)}</span>
          </div>
          ${thoughtsBlock}
          ${reflectionBlock}
        </div>`;
    })
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Georgia, serif; color: #1a1a1a; background: #FFFDF9; padding: 48px 56px; }
  h1 { font-size: 32px; color: #2D5016; margin-bottom: 4px; }
  .subtitle { font-family: Arial, sans-serif; font-size: 13px; color: #7a7a7a; margin-bottom: 40px; }
  .entry { margin-bottom: 40px; padding-bottom: 36px; border-bottom: 1px solid #E5DDD4; }
  .entry:last-child { border-bottom: none; }
  .entry-header { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 16px; }
  .entry-date { font-family: Arial, sans-serif; font-size: 13px; font-weight: bold; color: #2D5016; text-transform: uppercase; letter-spacing: 0.5px; }
  .mood-badge { font-family: Arial, sans-serif; font-size: 12px; color: #7a7a7a; background: #F0EBE4; padding: 3px 10px; border-radius: 12px; }
  .field { margin-bottom: 14px; }
  .field-label { font-family: Arial, sans-serif; font-size: 10px; font-weight: bold; color: #C2410C; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px; }
  .field-body { font-size: 15px; line-height: 1.8; color: #2a2a2a; }
  .footer { font-family: Arial, sans-serif; font-size: 11px; color: #aaa; text-align: center; margin-top: 48px; }
</style>
</head>
<body>
  <h1>Daily Journal</h1>
  <div class="subtitle">Exported on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })} · ${sorted.length} ${sorted.length === 1 ? "entry" : "entries"}</div>
  ${entriesHtml}
  <div class="footer">Generated by Daily Journal app</div>
</body>
</html>`;

  const { uri } = await Print.printToFileAsync({ html, base64: false });

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: "Export Journal",
      UTI: "com.adobe.pdf",
    });
  } else {
    throw new Error("Sharing is not available on this device");
  }
}
